### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by BrendanMonkey** [nanos-world/egui#1]
From what I'm aware of the close button isn't working, Not sure if I'm doing something wrong.
Yes, Inputs are being registered. 
I can't send a video right now, Though if one is required I'll send it over. 

```
    Package.RequirePackage("egui")
    Client.SetMouseEnabled(true)
    Client.SetInputEnabled(true)
    local window = EGUI.Window(20, 10, 600, 300, "Select Character", true, true)
 ```
 That's the code I'm using

**Comment by NegativeNameNGT** [comment]
You need to bind the event "CloseClick" and make the logic yourself
